### ISSUE TITLE
command "Rojo: initialize" throw an error

### ISSUE THREAD

**Issue by beijibeijing** [rojo-rbx/vscode-rojo#62]
when I use the command "Rojo: initialize" in Mac, it throw an error:
"spawnSync /Users/userName/Library/Application Support/Code/User/globalStorage/evaera.vscode-rojo/rojo-v6.2.0 Unknown system error -88".

**Comment by beijibeijing** [comment]
[error] Error: spawnSync /Users/beiji/Library/Application Support/Code/User/globalStorage/evaera.vscode-rojo/rojo-v6.2.0 Unknown system error -88
	at Object.spawnSync (node:internal/child_process:1083:20)
	at spawnSync (node:child_process:832:24)
	at Object.execFileSync (node:child_process:878:15)
	at Object.func (node:electron/js2c/asar_bundle:5:1812)
	at Rojo.init (/Users/beiji/.vscode/extensions/evaera.vscode-rojo-1.13.3/out/Rojo.js:112:22)
	at /Users/beiji/.vscode/extensions/evaera.vscode-rojo-1.13.3/out/commands/Initialize.js:22:10
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async o._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:31325) rojo.init {"value":"evaera.vscode-rojo","_lower":"evaera.vscode-rojo"}

**Comment by evaera** [comment]
Closing as the v1 branch has been deprecated
